### ISSUE TITLE
Issue for some ensdf files

### ISSUE THREAD

**Issue by Frozaccio** [IAEA-NSDDNetwork/RadiationReport#1]
Dear developers of RadiationReport,

Thank you very much for this program that is very nice to extract the specific radiations from a decay. 
I am using it for this purpose and it works very well for almost all the files. It helps me a lot for my radiation protection calculations or gamma spectroscopy report interpretations.

However, for some files I have issues that have 6 types of flavors.

Would you know how I can fix this ? Are there some issues in those ENSDF databases? 

Thank you very much for your help.
Thomas

Here are the issues:

**Type 1: example ensdf.011 from July 2024:**
```
java.lang.NullPointerException: Cannot read field "wk" because "this.atomic" is null
	at decay.DecayDataset.calculateRadiations(DecayDataset.java:1547)
	at decay.DecayDataset.<init>(DecayDataset.java:302)
	at decay.RadiationReport.start(RadiationReport.java:147)
	at main.Run.runRadReport(Run.java:121)
	at main.Main.runByCommand(Main.java:203)
	at main.Main.main(Main.java:30)
```

**Type 2: example ensdf.057 from July 2024**
```
java.lang.ArrayIndexOutOfBoundsException: 0 >= 0
	at java.base/java.util.Vector.elementAt(Vector.java:466)
	at ensdf.ENSDF.parentAt(ENSDF.java:5752)
	at decay.RadiationReport.start(RadiationReport.java:136)
	at main.Run.runRadReport(Run.java:121)
	at main.Main.runByCommand(Main.java:203)
	at main.Main.main(Main.java:30)
```

**Type 3: example ensdf.064 from July 2024**
```
java.lang.ClassCastException: class ensdf.ECBP cannot be cast to class ensdf.Beta (ensdf.ECBP and ensdf.Beta are in unnamed module of loader 'app')
	at decay.DecayDatasetGroup.findGridEnergyForIB(DecayDatasetGroup.java:673)
	at decay.DecayDatasetGroup.calculateContinua(DecayDatasetGroup.java:297)
	at decay.RadiationReport.processDatasetGroup(RadiationReport.java:289)
	at decay.RadiationReport.start(RadiationReport.java:165)
	at main.Run.runRadReport(Run.java:121)
	at main.Main.runByCommand(Main.java:203)
	at main.Main.main(Main.java:30)
```

**Type 4: example ensdf.069 from July 2024**
```
java.lang.NumberFormatException: For input string: "-9223372036854775808"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:588)
	at java.base/java.lang.Integer.valueOf(Integer.java:935)
	at ensdf.SDS2XDX.setValues(SDS2XDX.java:174)
	at ensdf.SDS2XDX.<init>(SDS2XDX.java:58)
	at decay.RadiationReport.writeToLogftReportAndOutput(RadiationReport.java:1301)
	at decay.RadiationReport.processDatasetGroup(RadiationReport.java:314)
	at decay.RadiationReport.start(RadiationReport.java:165)
	at main.Run.runRadReport(Run.java:121)
	at main.Main.runByCommand(Main.java:203)
	at main.Main.main(Main.java:30)
```

**Type 5: example ensdf.113 from July 2024**
```
java.lang.StringIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.lang.String.checkIndex(String.java:4881)
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:46)
	at java.base/java.lang.String.charAt(String.java:1582)
	at decay.DecaySpectrum.calculate(DecaySpectrum.java:1992)
	at decay.DecayDataset.calculateContinua(DecayDataset.java:2017)
	at decay.DecayDataset.<init>(DecayDataset.java:277)
	at decay.RadiationReport.start(RadiationReport.java:147)
	at main.Run.runRadReport(Run.java:121)
	at main.Main.runByCommand(Main.java:203)
	at main.Main.main(Main.java:30)
```

**Type 6: example ensdf.249 from July 2024**
```
java.lang.NullPointerException: Cannot read field "gKSQ" because "entry" is null
	at decay.DecaySpectrum.calculatefEC(DecaySpectrum.java:268)
	at decay.DecaySpectrum.calculateLogft(DecaySpectrum.java:703)
	at decay.DecaySpectrum.calculate(DecaySpectrum.java:1658)
	at decay.DecayDataset.calculateContinua(DecayDataset.java:2017)
	at decay.DecayDataset.<init>(DecayDataset.java:277)
	at decay.RadiationReport.start(RadiationReport.java:147)
	at main.Run.runRadReport(Run.java:121)
	at main.Main.runByCommand(Main.java:203)
	at main.Main.main(Main.java:30)

```

**Comment by FRIBNDC** [comment]
Dear Frozaccio,

Thanks for your feedback!

Those issues are either due to bugs in the code or associated with the ENSDF files. I have revised the code to take care of them. Please try the newly uploaded version and let me know if there is any other issue.

best,
Jun

**Comment by Frozaccio** [comment]
Thank you very much Jun. I did not expect you solved it so fast but now it is working very smoothly. I tested it on the full ENSDF database.

Best regards,
Thomas

**Comment by Frozaccio** [comment]
Dear Jun,

I have two additional questions, please.

**The first one is the following:**
I see in the radiation report that sometimes the decay time is not mentionned.
For example, we have
```
###########################################################################
        Radiation report for dataset: << 9LI B- DECAY >>
###########################################################################
```
while sometimes we have
```
###########################################################################
        Radiation report for dataset: << 11LI B- DECAY:8.75 MS >>
###########################################################################
```

Is this because the ENSDF file lacks of information or is there an option I may have triggered for one file and not the other? The decay time can help identifying the isomeric states.

**The second question is the following:**
Is there a way to increase the number of energy bins for the beta+/- spectrum ?

Thanks a lot for your precious help.
Best regards,
Thomas

**Comment by FRIBNDC** [comment]
Dear Thomas,

Thanks for asking.

The first question is related to the ENSDF file. In the examples, “9LI B- DECAY” and “11LI B- DECAY:8.75 MS” are simply the DSID (Dataset ID) taken from the first line of the ENSDF file, as a unique ID of the dataset. Sometimes an evaluator could give half-life at the end of the DSID and some doesn’t, for isotopes without isomer, for which case the decay dataset is the only dataset of this decay type, by default from the ground state decay. Giving T1/2 or not giving doesn’t matter in the evaluation for this case (for the purpose of identifying a dataset). But for isotopes with isomer(s), T1/2 must be given at the end of the DSID to differentiate this decay dataset from other decay datasets of the same type from the same parent but from different states.

T1/2 in the DSID of ENSDF decay datasets doesn’t really help identify the isomer parent, because T1/2 also appears in DSID for the decay of the parent in ground state. But one thing for sure is that: if there is no T1/2 in the DSID, the dataset must be for the decay of the ground state (unless there is no ground state having been discovered yet).

In summary for appearance of T1/2 in DSID of a decay dataset:
T1/2 may or may not appear in the DSID of the ground state decay.
T1/2 must appear in the DSID of an isomer decay.

But for your purpose, I will add a tag to indicate the decay is from an isomer. Since T1/2 always appear in DSID for isomer decay, I will add an isomer level energy as a tag.

For your second question about the binning of the B+/B- spectrum, the current binning is somewhat optimized to a level where the calculations would be reasonably quick but not very imprecise. Also note that incrementing bin sizes (as energy increases) instead of a common bin size are used to reduce calculation time (considering counts of betas decrease as energy increases). So, no option is provided for users to change the binning with previous versions.

I have added the following options in command line only to reset the binning :

“-EB_GRID_STEP=##” or “-EB_BIN_SIZE=##”: set initial bin size (low-energy end) for B-/B+ spectrum, default=2 keV
“-EIB_GRID_STEP=##” or “-EIB_BIN_SIZE=##”: set initial bin size for Internal Bremsstrahlung, default=20 keV

The bin-size is incremented by a factor after every 5 bins, the following is to set the factor
“-EB_GRID_MULTIPLIER=##”
“-EIB_GRID_MULTIPLIER=##”

If the resulting number of bins exceed the max number (default=30), the program will automatically adjust the step and multiplier until it finds the number of bins <=max number of bins. One can use “-MAX_NGRID=##” or “-MAX_NBINS=##” to reset the max number of bins.

The revised version has been uploaded into Github. Please keep in mind that the resetting might not work properly due to possible complications related to integrations.

Best,
Jun

**Comment by Frozaccio** [comment]
Thank you very much. I will be trying this and let you know.
Do I understand well that some radionuclides like         Radiation report for dataset: << 9LI B- DECAY >>  do not have half life in the ENSDF file and so it is not in the radiationreport ?

Thanks again.
Thomas

**Comment by FRIBNDC** [comment]
Hi Thomas,

For cases like <<9LI B- DECAY>> where half-life is not shown in the dataset ID, it is just that the half-life is not listed in that DSID by the evaluator, but the parent T1/2 does exist in the ENSDF file, so the radiation energies and intensities are still calculated by the program.

There could be datasets which may contains no or limited data for decay parent, like no decay T1/2. But the calculation of radiation energies and intensities are not based on T1/2 but on Q-value, decay branching ratio, individual level energy and decay feeding to the level, gamma intensities, etc. If there are no sufficient data for calculations, the updated version will add a comment for each corresponding radiation, like “can’t calculate X rays”.

A decay dataset would not in the report file if it has no decay data at all. For example, a decay dataset that only has comments (we do make some datasets (very rare) like that to tell readers that efforts have been made by researchers but no data has been obtained).

Best,
Jun

**Comment by Frozaccio** [comment]
Jun,

I have been running the new version of your code without any issues, trying different parameters for the beta spectrum. That is also very interesting for me to have the isomer level, which allows to recognize the isomeric state.

Thanks a lot for your detailed explanations. 
I understand better even if I am surprised the T1/2 of some isotopes like Li-9 is not in the evaluation; we can find the T1/2 in the literature.
I am not an experienced user of ENSDF and your code is perfect for me to extract data. 
I was having additional few questions below that could help me:
- Is there another location in ENSDF file where I can find the T1/2 when it is missing in the DSID?
- Is the branching ratio of the decay channel applied to the decay emissions in RadiationReport?
- Is there an option to extract neutron emissions or spontaneous fission?

Again, many thanks, that is strongly helping me.

**Comment by FRIBNDC** [comment]
Hi Thomas,

I’m very glad to know that you can now run the code without any issues, and thanks for your feedbacks.

For the case of 9Li B- decay, the T1/2 of 9Li is actually available in the parent record of the ENSDF dataset but is just not given in the DSID line of the dataset (used as the title you see in the report file). It will be a simple fix to add T1/2 in the title for cases like that, since now I know it is useful for users like you.

For your questions,

  *   Is there another location in ENSDF file where I can find the T1/2 when it is missing in the DSID?
I will add into the report file (the title) the missing T1/2 in DSID, like the case of 9Li B- decay

  *   Is the branching ratio of the decay channel applied to the decay emissions in RadiationReport?
Yes. Absolute emission intensities (per 100 decays of the parent through all decay channels) are used in the calculations.

  *   Is there an option to extract neutron emissions or spontaneous fission?
If you mean the branching ratios of neutron emissions (prompt or delayed) and SF, I can add them into the report file if there are available in the ENSDF dataset.

I will let you know when an updated version is available.

Best,
Jun

**Comment by FRIBNDC** [comment]
Hi Thomas,

Just realized that the branching ratios of neutron missions and spontaneous fissions of a parent nuclide are usually not given in a beta-decay dataset. They are available in the Adopted ENSDF dataset of a nuclide. So RadiationReport will not get those information since it only processes decay datasets. If you need those information of all nuclides or specific nuclides, I can extract those information from the ENSDF database and make a list of those data for you.

Best,
Jun

From: Chen, Jun
Sent: Friday, July 19, 2024 1:28 PM
To: 'IAEA-NSDDNetwork/RadiationReport' ***@***.***>; IAEA-NSDDNetwork/RadiationReport ***@***.***>
Cc: Assign ***@***.***>
Subject: RE: [IAEA-NSDDNetwork/RadiationReport] Issue for some ensdf files (Issue #1)

Hi Thomas,

I’m very glad to know that you can now run the code without any issues, and thanks for your feedbacks.

For the case of 9Li B- decay, the T1/2 of 9Li is actually available in the parent record of the ENSDF dataset but is just not given in the DSID line of the dataset (used as the title you see in the report file). It will be a simple fix to add T1/2 in the title for cases like that, since now I know it is useful for users like you.

For your questions,

  *   Is there another location in ENSDF file where I can find the T1/2 when it is missing in the DSID?
I will add into the report file (the title) the missing T1/2 in DSID, like the case of 9Li B- decay

  *   Is the branching ratio of the decay channel applied to the decay emissions in RadiationReport?
Yes. Absolute emission intensities (per 100 decays of the parent through all decay channels) are used in the calculations.

  *   Is there an option to extract neutron emissions or spontaneous fission?
If you mean the branching ratios of neutron emissions (prompt or delayed) and SF, I can add them into the report file if there are available in the ENSDF dataset.

I will let you know when an updated version is available.

Best,
Jun

**Comment by Frozaccio** [comment]
Thank you very much. I will wait for the update.

I realize my last question was not clear enough about neutron emissions. Indeed the BR and energy of neutron emission is of interest for me but not only.
I do not know if this information is available in ENSDF, but I am also looking for quantifying neutron decays from spontaneous fission. Hence, I am wondering if the spontaneous fission spectrum exists in ENSDF with its branching ratio or if I have to reconstruct it with Watt spectrum etc.. Also, those events are accompanied with delayed beta and gamma and I do not know if this information is in the ENSDF file to differentiate standard and delayed emissions.

Best regards,
Thomas

**Comment by FRIBNDC** [comment]
Hi Thomas,

From my understanding, I assume you are looking neutron emissions from the decays of fission products of spontaneous fission of a nuclide, say 252CF. In ENSDF, we have datasets like “252CF SF DECAY” in which there are usually the level and gamma data of specific nuclide from the spontaneous fission of 252CF, like 150Ce. If a nuclide in the fission products subsequently undergoes neutron emission (prompt or delayed), the neutron data (energy and emission probability) and gamma data associated with the neutron emission if also measured will be stored in a dedicated neutron decay dataset, for example, “29NA B-N DECAY”, where all neutrons detected to be emitted following beta- decay of 29Na and the final levels in the daughter nuclide 28Mg are stored. From such datasets, one can get the neutron emission probabilities per 100 29Na decays, but would have no way to get the neutron emission probabilities relative to the number of spontaneous fissions if the decay parent is produced from the spontaneous fissions.

I’m not sure if that is related to the fission product yield data. If so, you would probably need to refer to the ENDF database for those data.

Best,
Jun

**Comment by FRIBNDC** [comment]
Hi Thomas,

The updated version has been uploaded to Github. I added into the report file a line under the title line to list the information of the decay parent: level energy, T1/2, decay branching ratio, Q-value.

Best,
Jun

**Comment by Frozaccio** [comment]
Jun,

Thank you for the updated code that I will test this weekend.
Regarding the neutron decay, I will dig a bit more and see what I can find.

Best regards,
Thomas

**Comment by Frozaccio** [comment]
Dear Jun,

Thanks for still reading my questions which show my ignorance.
It required a bit more time than I expected to come back to you but I now have a bunch of questions I hope you can help me with. I have not yet had the time to look at the spontaneous fissions in details but I am interested in better understanding the results I got with your program.
I will illustrate with some examples since it will make it easier. Those examples are maybe not the best ones since they are related to very short half lives radionuclides, maybe the response to my question is just “the evaluation lacks data” in such case, I will have to find a way to exclude those radionuclides. Or maybe I can look on the side of XUNDL which I have not yet considered because I have not read enough to know what it is.
**Questions 1. Example with 14Be**
```
########################################################################################
      Radiation report for dataset: << 14BE B-N DECAY >>
########################################################################################
*** Parent level: E=0 keV *T1/2=4.31(24) MS *branching(%)=94(5) *Q-value=1.532E4(13)
             List of Energies and Intensities of All Radiations             
            (multiply 2.13 to convert dose unit to G-Rad/uCi-h)             
----------------------------------------------------------------------------
Radiation               Energy             Intensity             Dose     
   Type                 (keV)                  %              (MeV/Bq-s)  
----------------------------------------------------------------------------
B-N 1                288        1        91.0       90       0.262     26
B-N 2                3.02E3     3        0.110      50       0.0033    16
AUGER                can't calculate radiations for auger electrons
X-RAY                can't calculate radiations for X rays
GAMMA  1             3536       2        0.90       30       0.032     11
```

The branching provided in the parent level is 94 % from the ensdf.013 file. However, when I look in the table, I see the maximum intensity is 91 %. Even doing the some of all intensities, I will find only 92 %. In addition, if I look in the literature, for example here (https://www.chemlin.org/isotope/beryllium-14) I see a branching for the neutron decay of 81 % + 5 % = 86 % and when I look in the ensdf.014 file, I can see the following lines  which seem compatible to what is in the literature. 
```
14BE cL T$From 1988DuZT. Others: 4.2 s {I7} (1986Cu01), 4.29 s {I18} (1997Be66)
 14BE2 L %B-=100$ %B-N=81 4$ %B-2N=5 2$                                         
 14BE cL           %|b{+-} not followed by neutron decay is 14 {I3}    
```

- Is there a reason for this branching to be 94 %? May I ask you how this is found or if the meaning is different from the one I found in the literature?
- Also, in this decay, the radiation named “B-N” gives the energy and intensity of the neutrons, while the beta spectrum is obtained from the “B-“ decay found in the ensdf.014 file, am I correct? 
- In this case, the radiations from decay of 14Be is obtained by simply merging those two channels radiations? 

**Questions 2. Example with 62Mn** 
Looking at the ensdf.062 file, I can find two radionuclides 62Mn
```
########################################################################################
      Radiation report for dataset: << 62MN B- DECAY (671 MS) >>
########################################################################################
*** Parent level: E=0+y keV *T1/2=671(5) MS *branching(%)=100 *Q-value=1.0354E4(7)
########################################################################################
      Radiation report for dataset: << 62MN B- DECAY (92 MS) >>
########################################################################################
*** Parent level: E=0+x keV *T1/2=92(13) MS *branching(%)=100 *Q-value=10697.1(38)
```
The energy levels are respectively 0+y and 0+x. I know from the literature that the isomeric state is the one with 92 ms T1/2 so, the 0+x level. How can I distinguish isomeric states when this case happens and the level is 0+x, 0+y, x, y, 0+v, etc… ?

**Question 3.**
When RadiationReport writes “can’t calculate radiations for XXX”, is it because information is missing in the ensdf file or is it because this radiation does not exist ?

**EDIT: Question 4.**
I checked in the ENSDF database and it seems the spontaneous fission decay is available. I don't know exactly which information is provided in ENSDF but I can see the branching ratio (e.g. for CF-252 in ensdf.252):
```
252CF    ADOPTED LEVELS, GAMMAS                                  21NDS    202103
252CF  H TYP=FUL$AUT=A.M. MATTERA, S. ZHU, A.B. HAYES, E.A. MCCUTCHAN$          
252CF2 H CIT=NDS 172, 543 (2021)$CUT=1-Jan-2021$                                
252CF  Q -1.26E+3  5  6172   4  6482   11 6216.95 4    2017WA10                 
[...]
252CF  L 0.0          0+                2.647 Y   3                         E   
252CFX L XREF=ABCD                                                              
252CF2 L %A=96.898 3$%SF=3.102 3                                                
```
Is RadiationReport recognizing this decay channel ?


Thank you again
Best regards

**Comment by FRIBNDC** [comment]
Hi Thomas,

Thanks again for your valuable feedbacks!

First, let me explain ENSDF and XUNDL databases:
ENSDF: contains evaluated experimental structure and decay data, organized by mass chains (nuclides with same mass number); then for each nuclide, it contains an Adopted dataset with recommended values based on all data in the individual decay and reaction datasets that follow the Adopted dataset. Each mass chain evaluation is usually updated roughly every 10 years due to very time-consuming effort for evaluation and manpower shortage. The whole mass region (mass number A=1 to 300) is split into sub-regions and assigned to different nuclear data centers in US and other countries in the international Nuclear Structure and Decay Data evaluator network under IAEA.

XUNDL: (complement to ENSDF database) contains only unevaluated data, promptly compiled from recently published papers. This database was created as a complement to the ENSDF database, because of the long update cycle (~10 year) of ENSDF mass-chain evaluations and the demand of new data. The data in a journal paper was promptly compiled into a dataset in ENSDF-style format (simply compilation without any evaluation) and stored in the XUNDL dataset. So basically, each dataset in the XUNDL database corresponds to a paper (one paper could have multiple datasets because it could study multiple nuclides). It serves as a repository of the newly published data and usually also a starting point for mass-chain evaluation.

Please see below my answers to your questions.
Quqestion1: about inconsistent %B-N

  *   Is there a reason for this branching to be 94 %? May I ask you how this is found or if the meaning is different from the one I found in the literature?
Answer: this inconsistency in %B-1N (94% from the 14Be parent record in “14Be B-N decay” dataset in ensdf.013 and %81 from 14Be “Adopted Levels” dataset in esdf.014) is because they are from two separate mass-chain evaluations: A=13 and A=14. The evaluation of A=13 was last updated in 2013 (where the evaluators also updated the %B-N of the 14Be parent) while A=14 was still the update in 1990 and is very outdated and currently under evaluation.  The %B-1N=94(5) is taken by the evaluator from the reference (NSR keynumber=1997AO04): Z.Phys. A 358, 253 (1997), as noted in a comment in the dataset of 14BE B-N DECAY, while the values of %B-1N=81 and %B-2N=5 are from an older reference (1988DU09): Phys.Lett. 206B, 195 (1988), which is not mentioned in 14Be Adopted dataset, but in 14BE B-N Decay dataset.

So, the inconsistency is due to the out-of-sync of A=13 and A=14 evaluations. This issue commonly exists in ENSDF database and we’ve been discussing about and looking for practical solutions to solve issues like this.


  *   Also, in this decay, the radiation named “B-N” gives the energy and intensity of the neutrons, while the beta spectrum is obtained from the “B-“ decay found in the ensdf.014 file, am I correct?
Answer: Yes. For decay data stored in ENSDF, the data are always directly associated with the final decay daughter, except for those data specified in the records of the decay parent. So “B-N” dataset stores data of neutrons to and levels of the final daughter; “B-“ or “B+/EC” datasets have the data of B- or B+/EC decays to and levels of the final daughter.
This program processes the two datasets in this example separately.

  *   In this case, the radiations from decay of 14Be is obtained by simply merging those two channels radiations?
Answer: No, by default. This program processes the two datasets separately, by default. To merge datasets with the same parent, you can add an option “-merge” in the command line or check the “merge decays of same parent” box in the GUI window.

Question 2. Example with 62Mn

Answer:

The current evaluation in the database is from 2012 update which doesn’t tell which one is the ground state and which is the isomer based on available data at that time. The new update has been completed and is currently under review. New data after 2012 update is available in the XUNDL database, where the work by 2015GA38: Eur. Phys. J. A51, 136 (2015) fixes the one with T1/2=92 ms and JPI=(1+) to be the ground state and the 671-ms level to be the isomer.
In general, if there are only 0+x, 0+y,…, levels with isomeric half-lives but no E=0 state (ground state) in the ENSDF database, it is just that there is no sufficient experimental evidence to identify the ground and isomeric states when the evaluation was done, but they may have been identified later after the last ENSDF update, like this 62Mn case. Again, this is due to the ENSDF evaluation being lagging behind. We are seeking solutions to improve this situation, like nuclide-by-nuclide evaluation instead of evaluation of a whole mass chain to reduce the length of evaluation cycle.

If there is a E=0 state, all levels with E=0+x, 0+y, … and isomeric T1/2 are isomeric states.


Question 3.
When RadiationReport writes “can’t calculate radiations for XXX”, is it because information is missing in the ensdf file or is it because this radiation does not exist ?

Answer:
It means this kind of radiation does exist, but the intensities are not available, either omitted because of negligibly small intensities or because information is missing or unknown in the ENSDF file, like the example of 14BE B-N decay dataset, for which the atomic K shell of 13B daughter exists, but the needed K shell information is not available in the dataset, that is, the K shell conversion coefficient needed to calculate the Auger and thus the X-ray intensity from the measured gamma intensity. The absence of such information is because the multipolarity (M1, E2, or E1, M2) of this gamma is unknown which is needed by the BrIcc code to calculate the sub-shell conversion coefficients.

I have revised the message of “can’t calculate radiations” to make it clearer. The updated version is now available in the NSDD github.

Best,
Jun

**Comment by Frozaccio** [comment]
Thank you again Jun for your very detailed answer.

I understand that extracting the data from ENSDF to have an accurate decay information is not as straightforward as I thought. I will give a try with XUNDL that I better understand with your explanation.

I also understand that the merge option of RadiationReport will require that I merge the ENSDF files into one so that the code can identify the decay channels of one radionuclide due to channels being in separate mass chain evaluation.

Maybe you have not seen my question 4 because I edited my message afterwards but I was also wondering why the Spontaneous Fission decay was not found by RadiationReport.
For example in ensdf.123, there is this line (you mentioned it previously for 150CE as well) "123CD    252CF SF DECAY                2002HW01                  21NDS    202105" but in the associated report from the code, this decay channel is not provided. In the ICRP107, those decays are provided with a branching ratio but I don't know if ICRP107 extracted this data from ENSDF.

Best regards,
Thomas

**Comment by FRIBNDC** [comment]
Hi Thomas,

I didn’t see Question 4 since it is not in the email.

Thanks for the feedback about the spontaneous fission. I have to admit that I had never thought about that before for this code. Perhaps I can use some suggestions based on your needs and expertise about what to calculate and include in the report.

The original legacy Fortran code (RADLIST) was designed to calculate radiations for the common radioactive decays, like B-, EC/B+, alpha, and associated gammas. It seems to me that other decays, like spontaneous decay, cluster decay, are not included. This Java code follows that.

For the example of 252Cf SF DECAY to 123Cd, there are only a few gamma rays with relative intensities. From my understanding, no meaningful radiation energies and intensities (doses) can be calculated for them, unlike those radiations in B-, EC/B+ and alpha decays where there are decay Q-value and absolute decay intensities. This again makes me think about the fission yield database of the reaction data program, even though I’m not from that background. Perhaps there could be some meaningful data for calculating radiations (average energy and intensity?). For this example, I would assume the nuclide of interest is 252Cf for which the fission energies and intensities (yields) are wanted. But data (reaction data) needed for such calculations don’t exist and are not included in the ENSDF or XUNDL databases for nuclear structure data.

The decay branching ratios are taken into account for calculating radiation energies and intensities of those common decays.

Best,
Jun

**Comment by FRIBNDC** [comment]
Hi Thomas,

I just looked at ICRP 107 you mentioned in your email for 252Cf and it is interesting to know ENSDF is used in this application. I heard about that before and haven’t never seen the actual calculations. I guess most of ENSDF evaluators don’t know their evaluations could have been in areas they don’t know, other than nuclear structure research. This is encouraging to us.

For the 252Cf case, there are an alpha decay dataset and a SF decay dataset in the input file “cf252.ens”. In the “Cf252.out” (it is interesting to know similar calculations for radiations are done here), it looks to me that those results of radiation calculations are basically based on the alpha decay dataset. The SF decay dataset doesn’t provide extra information. The SF branching ratio is simply equal to 100-%alpha in the alpha decay dataset, which should have been taken into account in the calculations of alpha decay dataset.

I noticed a record line in the SF dataset:
“252CF  F 3.765       3.092E+0          1.02500E+00         2.92600E+0 “

This is not what I can recognize in our standard ENSDF format, and I guess it could be created by ICRP for their purpose.

Also %SF=3.09 in ICRP is slightly different from the current %SF=3.102(3) in ENSDF database, because the former value seems to be taken from 1999 update of A=252 ENSDF evaluation, while the latter is from a new ENSDF evaluation in 2021.

In the “252CF SF DECAY” dataset of 123Cd, no branching is given because it is unknown (from my guess) for this SF channel to 123Cd, while %SF=3.09 is for the overall SF decay of 252CF, which have multiple channels to different fission products.

Best,
Jun

**Comment by Frozaccio** [comment]
Dear Jun,

Thank you for your messages.
I did some research regarding the ICPR107 SF reconstruction and I particularly found nice information in this document : https://inis.iaea.org/collection/NCLCollectionStore/_Public/36/113/36113475.pdf?r=1

My understanding is as follows:
-As you mentioned, there is no specific branching ratio for CF252->CD123. I think this makes sense because CD123 is one possible fission product among a lot of others and so the branching would be very low. It is quite easy to derive the fission products branching ratios from the nuclear cross-section database if we have the branching ratio of the decay, detailing in how many of the decays a radionuclide undergoes spontaneous fissions.

-From the document I sent above, it seems that the spontaneous fission neutron spectrum is derived in a quite similar way than what we do with the standard fission neutron spectrum. The authors in the document assume a watt spectrum with some parameters they found in the literature

-It is not yet clear to me how they derive the prompts and delayed {gamma, beta, neutrons} with those equations but if it is similar to standard fission, I think I could extract it. The authors explain they compute the average energy and intensities of those radiations but, when looking in the ICRP107 database, the radiations are represented by a discrete spectrum. The equations provided do not seem to give a vector, rather a scalar so, I think it is really the average characteristics. I have not clue on how they compute the spectrum.


I have tried to find the code they mention, EDISTR04 but found nothing so far.
As you wrote, the SF radiations are not in ENSDF and I am sure it is possible to reproduce them with some significant efforts but then the branching ratio of the decay channel is still missing and the only way is to calculate via 1-sum(other decay channels) which is not safe in case ENSDF has not all the decay channels in the evaluations.

Best regards,
Thomas

**Comment by FRIBNDC** [comment]
Hi Thomas,

Thanks for sending me the link of the document. It could be very helpful regarding those calculations which are not included in the RadiationReport code or the legacy RADLIST code.

From this document about spontaneous fission radiations, it seems to me that those calculations (total or averaged energies and intensities of fission fragments, prompt and delayed gammas, neutrons, betas) used in the EDISTR code are straightforward, from simple analytical formula,  but are mostly empirical or estimated.  As you pointed out, it is not clear how those empirical formulae are derived, so their reliability might be questionable, but perhaps the estimation is good enough to serve the purpose (just from my point of view as a non-expert in SF and nuclear reaction data).

From ENSDF data point of view, the only data that is used in the calculations of SF radiations is the SF branching ratio, which is given as the total branching ratio of all SF channels of the parent nucleus, not a specific SF channel. So there should be no concern about missing SF channels of a nucleus in ENSDF for calculations of the total SF energy and intensity according to the formula in the EDISTR document. But calculations of radiations for a specific SF channel are impossible using ENSDF data and seems not available in EDISTR either.

From the document, the EDISTR only calculates the neutron spectrum using the Eq.(3.8) approximated for the Watt spectrum, and for others (gammas and betas) it only calculates the average energies and intensities.

Best,
Jun
